# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=8)),
                ('estimated_time_departure', models.DateTimeField()),
                ('estimated_time_arrival', models.DateTimeField()),
                ('location_departure', models.CharField(max_length=3)),
                ('location_arrival', models.CharField(max_length=3)),
                ('airline', models.CharField(max_length=3)),
                ('aircraft', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
