# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('airline', models.CharField(max_length=3)),
                ('construction_date', models.DateField()),
                ('first_flight_date', models.DateField()),
                ('maximum_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=3)),
                ('telephone', models.CharField(max_length=9)),
                ('year_foundation', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('aircraft', models.CharField(max_length=4)),
                ('number_of_passengers', models.IntegerField()),
            ],
        ),
    ]
