# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0003_auto_20170410_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Aircraft'),
        ),
    ]
