# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0005_auto_20170410_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Airline'),
        ),
    ]
