# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0006_auto_20170410_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ManyToManyField(to='flylo.Airline'),
        ),
    ]
