# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0008_auto_20170410_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='airlines',
            field=models.ManyToManyField(to='flylo.Airline'),
        ),
    ]
