# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0009_auto_20170416_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='airline',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='construction_date',
            field=models.DateField(verbose_name='Construction date'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='first_flight_date',
            field=models.DateField(verbose_name='Date of first flight'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='maximum_speed',
            field=models.FloatField(verbose_name='Maximum speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='country',
            field=models.CharField(max_length=8, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=3, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='telephone',
            field=models.CharField(max_length=9, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='year_foundation',
            field=models.CharField(max_length=4, verbose_name='Foundation year'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=12, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='number_of_passengers',
            field=models.IntegerField(verbose_name='Number of passengers'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_arrival',
            field=models.DateTimeField(verbose_name='Estimated arrival'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_departure',
            field=models.DateTimeField(verbose_name='Estimated departure'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=8, verbose_name='Flight number'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='location_arrival',
            field=models.CharField(max_length=3, verbose_name='Location arrival'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='location_departure',
            field=models.CharField(max_length=3, verbose_name='Location departure'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=40, verbose_name='Current state'),
        ),
    ]
