# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0010_auto_20170416_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='long_name',
            field=models.CharField(default='a', max_length=20, verbose_name='Long Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=3, verbose_name='Short Name'),
        ),
    ]
