# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0016_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flights',
            field=models.ManyToManyField(to='flylo.Flight'),
        ),
    ]
