# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0017_client_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='flights',
        ),
    ]
