# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0018_remove_client_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('flight_number', models.CharField(max_length=8, verbose_name='Flight number')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='CheckIn realized')),
            ],
        ),
    ]
