# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0020_auto_20170426_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientflights',
            name='airline',
            field=models.CharField(default='Iberia', max_length=20, verbose_name='Airline'),
        ),
    ]
