# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0021_clientflights_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientflights',
            name='airline',
        ),
        migrations.AddField(
            model_name='clientflights',
            name='seats',
            field=models.IntegerField(default=1, verbose_name='Number of seats'),
        ),
    ]
