# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0022_auto_20170427_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientflights',
            name='airline',
            field=models.CharField(default='', max_length=20, verbose_name='Airline'),
        ),
    ]
