# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0023_clientflights_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientflights',
            name='status',
            field=models.CharField(default='Acquired', max_length=20, verbose_name='Flight status'),
        ),
    ]
