# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0024_clientflights_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
        migrations.AddField(
            model_name='flight',
            name='distance',
            field=models.FloatField(default=400.0, verbose_name='Flight Distance (km)'),
        ),
    ]
