# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0026_auto_20170428_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='seats_occupied',
            field=models.CharField(default='', max_length=1000, verbose_name='Seats occupied'),
        ),
    ]
