# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0027_flight_seats_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientflights',
            name='passengers_names',
            field=models.TextField(default='', verbose_name='Names of passengers'),
        ),
    ]
