# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 08:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flylo', '0031_auto_20170505_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
