# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0032_auto_20170511_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='highlighted',
        ),
    ]
